# Site settings
title: CppCompile - 12-Week Accelerated C++ Compiler Developer Guide
description: A comprehensive guide for transitioning from basic programming to systems-level C++ development
baseurl: "/CppCompile" # the subpath of your site
url: "https://vnmrsharma.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge
remote_theme: pages-themes/cayman@v0.2.0

# Cayman theme configuration
show_downloads: false
google_analytics: # Add your Google Analytics tracking ID here if desired

# GitHub metadata
github:
  repository_url: https://github.com/vnmrsharma/CppCompile
  zip_url: https://github.com/vnmrsharma/CppCompile/archive/main.zip
  tar_url: https://github.com/vnmrsharma/CppCompile/archive/main.tar.gz

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap